/**
 * ============================================================================
 * DISNEY_DATA — 도쿄 디즈니랜드(tdl) / 도쿄 디즈니씨(tds) 파크 지도의 데이터
 * ============================================================================
 * 두 파크는 완전히 분리된 네임스페이스(tdl/tds)를 쓰고, 절대 서로 데이터를
 * 섞지 않는다(지도 중심, bounds, 어트랙션, 화장실, 마커, 경로 전부 별도).
 *
 * 모든 좌표는 Playwright로 구글맵에 접속해 "정식 명칭 + 東京ディズニーランド"를
 * 검색한 뒤 @lat,lng와 표시된 장소명/주소를 교차검증해서 확인한 값만 넣었다.
 * 후보 목록에 있었지만 실제로는 미국 파크 매장이거나(Big Top Souvenirs,
 * Star Trader, Tony's Town Square) 폐점/개명된 곳(Mickey's PhilharMagic →
 * Mickey's Magical Music World, Toontown Five & Dime → Gag Factory/Five &
 * Dime, "Swift Rabbit Cafe" → 실존하지 않아 Hungry Bear Restaurant로 대체)은
 * 검증 과정에서 걸러내거나 실제 존재하는 이름으로 바로잡았다.
 *
 * 사용자가 제공한 공식 파크 가이드맵 PDF(TDL_map_kr.pdf)를 직접 열어 분석한
 * 결과, 이 목록에 없는 어트랙션(스플래시 마운틴, 엔체인티드 티키룸 등)과
 * 월드바자 상점 다수가 지도에 더 있는 것을 확인했다 — 이번 범위는 "주요
 * 어트랙션/대표 상점"으로 의도적으로 좁힌 1차 조사 결과이며, 확장은 별도
 * 조사 작업으로 진행한다(추측 좌표 추가 금지 원칙은 동일하게 적용).
 *
 * 도쿄 디즈니씨(tds)는 이번에 TDS_map_kr.pdf를 분석해 테마포트 구조와 주요
 * 어트랙션 이름은 파악했지만, 단 하나의 좌표도 구글맵으로 검증하지 않았다.
 * facilities를 비워두고 좌표를 임의로 만들지 않는다 — 별도 조사 후 채운다.
 *
 * rating(1~5)은 구글맵 등 외부 평점이 아니라, 인지도/인기를 참고해 이 앱에서
 * 임의로 매긴 "추천 지표"다. darkRide/thrillLevel/indoor도 같은 성격의
 * 일반 상식 수준 분류이며(공식 안전 정보 아님), 반면 minimumHeight/
 * mustBeAccompanied/strollerParkingNearby는 실제로 탑승 가능 여부를 좌우하는
 * 안전 정보라서 공식 텍스트로 재검증하기 전까지는 전부 null(확인 필요)로
 * 남겨둔다 — js/disney.js의 FACILITY_DEFAULTS가 모든 시설에 이 필드들의
 * 기본값을 채워 넣으므로 이 파일에는 실제로 아는 값만 적는다.
 *
 * category: 'attraction' | 'restaurant' | 'shop' | 'restroom'
 * ============================================================================
 */
const DISNEY_DATA = {
  tdl: {
    key: "tdl",
    name: "도쿄 디즈니랜드",
    coords: [35.6329, 139.8804],
    mapPdf: "TDL_map_kr.pdf",
    facilities: [
      // ----------------------------------------------------------------
      // 어트랙션
      // ----------------------------------------------------------------
      {
        id: "jungle-cruise",
        name: "정글 크루즈",
        japaneseName: "ジャングルクルーズ：ワイルドライフ・エクスペディション",
        category: "attraction",
        area: "어드벤처랜드",
        coords: [35.6338132, 139.8822097],
        googleMapsQuery: "ジャングルクルーズ 東京ディズニーランド",
        description: "정글을 탐험하며 야생동물 애니매트로닉스를 만나는 보트 투어 어트랙션",
        recommendedTime: "약 9분",
        rating: 4,
        indoor: false,
        darkRide: false,
        thrillLevel: 1,
        highlights: ["능청스러운 선장의 라이브 유머 해설", "리뉴얼된 화려한 야생동물 연출"],
      },
      {
        id: "pirates-caribbean",
        name: "카리브의 해적",
        japaneseName: "カリブの海賊",
        category: "attraction",
        area: "어드벤처랜드",
        coords: [35.6342439, 139.8807329],
        googleMapsQuery: "カリブの海賊 東京ディズニーランド",
        description: "해적들의 세계를 항해하며 둘러보는 보트형 다크라이드",
        recommendedTime: "약 15분",
        rating: 5,
        indoor: true,
        darkRide: true,
        thrillLevel: 1,
        highlights: ["디즈니 파크 최장급 보트 다크라이드", "실감나는 해적선 전투와 보물 창고 장면"],
      },
      {
        id: "swiss-family-treehouse",
        name: "스위스 패밀리 트리하우스",
        japaneseName: "スイスファミリー・ツリーハウス",
        category: "attraction",
        area: "어드벤처랜드",
        coords: [35.6333103, 139.8817408],
        googleMapsQuery: "スイスファミリー・ツリーハウス 東京ディズニーランド",
        description: "거대한 나무 위에 지어진 로빈슨 가족의 집을 걸어서 둘러보는 워크스루 어트랙션",
        recommendedTime: "약 10~15분",
        rating: 3,
        indoor: false,
        darkRide: false,
        thrillLevel: 1,
        highlights: ["높은 곳에서 바라보는 어드벤처랜드 전망", "가족의 생활상을 재현한 아기자기한 소품들"],
      },
      {
        id: "western-river-railroad",
        name: "웨스턴 리버 철도",
        japaneseName: "ウエスタンリバー鉄道",
        category: "attraction",
        area: "어드벤처랜드",
        coords: [35.6337158, 139.8823306],
        googleMapsQuery: "ウエスタンリバー鉄道 東京ディズニーランド",
        description: "증기기관차를 타고 파크 외곽을 한 바퀴 도는 순환 열차 어트랙션",
        recommendedTime: "약 13분",
        rating: 3,
        indoor: false,
        darkRide: false,
        thrillLevel: 1,
        highlights: ["공룡 디오라마와 그랜드캐니언 풍경 감상", "이동 수단이자 관람용으로도 즐길 수 있음"],
      },
      {
        id: "big-thunder-mountain",
        name: "빅 선더 마운틴",
        japaneseName: "ビッグサンダー・マウンテン",
        category: "attraction",
        area: "웨스턴랜드",
        coords: [35.6324683, 139.8835266],
        googleMapsQuery: "ビッグサンダー・マウンテン 東京ディズニーランド",
        description: "폐광촌을 질주하는 광산 열차 콘셉트의 패밀리 롤러코스터",
        recommendedTime: "약 4분",
        rating: 5,
        indoor: false,
        darkRide: false,
        thrillLevel: 2,
        highlights: ["아이도 즐길 수 있는 적당한 스릴", "정교하게 재현된 서부 광산촌 세트"],
      },
      {
        id: "mark-twain-riverboat",
        name: "마크 트웨인호",
        japaneseName: "蒸気船マークトウェイン号",
        category: "attraction",
        area: "웨스턴랜드",
        coords: [35.6316174, 139.8829813],
        googleMapsQuery: "マークトウェイン号 東京ディズニーランド",
        description: "미시시피강을 재현한 리버스 오브 아메리카를 순회하는 증기선 유람",
        recommendedTime: "약 16분",
        rating: 3,
        indoor: false,
        darkRide: false,
        thrillLevel: 1,
        highlights: ["선상 갑판에서 즐기는 여유로운 경치 감상", "웨스턴랜드 곳곳의 풍경을 물 위에서 조망"],
      },
      {
        id: "tom-sawyer-island-rafts",
        name: "톰소여 섬의 뗏목",
        japaneseName: "トムソーヤ島いかだ",
        category: "attraction",
        area: "웨스턴랜드",
        coords: [35.6319708, 139.883733],
        googleMapsQuery: "トムソーヤ島いかだ 東京ディズニーランド",
        description: "뗏목을 타고 톰소여의 섬으로 건너가 자유롭게 탐험하는 체험형 어트랙션",
        recommendedTime: "뗏목 이동 약 2분 + 섬 탐험 자유",
        rating: 3,
        indoor: false,
        darkRide: false,
        thrillLevel: 1,
        highlights: ["동굴과 흔들다리 등 숨은 탐험 요소", "아이들이 직접 뛰어놀 수 있는 야외 공간"],
      },
      {
        id: "country-bear-theater",
        name: "컨트리 베어 시어터",
        japaneseName: "カントリーベア・シアター",
        category: "attraction",
        area: "웨스턴랜드",
        coords: [35.6324942, 139.8823899],
        googleMapsQuery: "カントリーベア・シアター 東京ディズニーランド",
        description: "곰 캐릭터들이 펼치는 코믹한 애니매트로닉스 뮤지컬 쇼",
        recommendedTime: "약 15분",
        rating: 3,
        indoor: true,
        darkRide: false,
        thrillLevel: 1,
        highlights: ["익살스러운 곰들의 컨트리 음악 공연", "실감나는 애니매트로닉스 연출"],
      },
      {
        id: "beaver-brothers-canoes",
        name: "비버 브라더스의 카누 탐험",
        japaneseName: "ビーバーブラザーズのカヌー探険",
        category: "attraction",
        area: "크리터컨트리",
        coords: [35.6309433, 139.8838742],
        googleMapsQuery: "ビーバーブラザーズのカヌー探険 東京ディズニーランド",
        description: "손님이 직접 노를 저어 리버스 오브 아메리카를 탐험하는 체험형 카누 어트랙션",
        recommendedTime: "약 6분",
        rating: 3,
        indoor: false,
        darkRide: false,
        thrillLevel: 1,
        highlights: ["직접 노를 젓는 참여형 체험", "날씨/시즌에 따라 운영되는 한정 어트랙션"],
      },
      {
        id: "small-world",
        name: "이츠 어 스몰 월드",
        japaneseName: "イッツ・ア・スモールワールド",
        category: "attraction",
        area: "판타지랜드",
        coords: [35.6307756, 139.8810621],
        googleMapsQuery: "イッツ・ア・スモールワールド 東京ディズニーランド",
        description: "세계 각국의 인형과 노래로 꾸며진 실내 보트 투어",
        recommendedTime: "약 14분",
        rating: 5,
        indoor: true,
        darkRide: true,
        thrillLevel: 1,
        highlights: ["전 세계 어린이 인형이 함께 부르는 시그니처 송", "화려한 색감의 실내 장식"],
      },
      {
        id: "peter-pan-flight",
        name: "피터팬의 비행",
        japaneseName: "ピーターパン空の旅",
        category: "attraction",
        area: "판타지랜드",
        coords: [35.6317697, 139.8818488],
        googleMapsQuery: "ピーターパン空の旅 東京ディズニーランド",
        description: "해적선을 타고 런던 야경에서 네버랜드까지 하늘을 나는 다크라이드",
        recommendedTime: "약 3분",
        rating: 5,
        indoor: true,
        darkRide: true,
        thrillLevel: 1,
        highlights: ["하늘을 나는 듯한 독특한 탑승감", "런던에서 네버랜드로 이어지는 스토리 연출"],
      },
      {
        id: "snow-white-adventures",
        name: "백설공주와 일곱 난쟁이",
        japaneseName: "白雪姫と七人のこびと",
        category: "attraction",
        area: "판타지랜드",
        coords: [35.631696, 139.8813408],
        googleMapsQuery: "白雪姫と七人のこびと 東京ディズニーランド",
        description: "백설공주 이야기를 따라가는 트랙형 다크라이드",
        recommendedTime: "약 3분",
        rating: 3,
        indoor: true,
        darkRide: true,
        thrillLevel: 1,
        highlights: ["동화 장면을 그대로 재현한 세트", "마녀 등장 등 은근한 스릴 요소"],
      },
      {
        id: "pinocchio-journey",
        name: "피노키오의 모험 여행",
        japaneseName: "ピノキオの冒険旅行",
        category: "attraction",
        area: "판타지랜드",
        coords: [35.6309842, 139.8805325],
        googleMapsQuery: "ピノキオの冒険旅行 東京ディズニーランド",
        description: "피노키오의 모험을 따라가는 다크라이드",
        recommendedTime: "약 3분",
        rating: 3,
        indoor: true,
        darkRide: true,
        thrillLevel: 1,
        highlights: ["피노키오 이야기를 따라가는 트랙형 라이드", "고래 몬스트로 장면의 스릴"],
      },
      {
        id: "dumbo-flying-elephant",
        name: "덤보의 하늘을 나는 대모험",
        japaneseName: "ダンボの空飛ぶ大冒険",
        category: "attraction",
        area: "판타지랜드",
        coords: [35.6314556, 139.8816977],
        googleMapsQuery: "ダンボの空飛ぶ大冒険 東京ディズニーランド",
        description: "덤보 모양 탑승체를 타고 빙글빙글 돌며 높낮이를 조절하는 회전 라이드",
        recommendedTime: "약 2분",
        rating: 3,
        indoor: false,
        darkRide: false,
        thrillLevel: 1,
        highlights: ["아이가 직접 높낮이를 조절하는 재미", "파스텔톤의 사랑스러운 비주얼"],
      },
      {
        id: "alice-tea-party",
        name: "앨리스의 티 파티",
        japaneseName: "アリスのティーパーティー",
        category: "attraction",
        area: "판타지랜드",
        coords: [35.6311505, 139.88097],
        googleMapsQuery: "アリスのティーパーティー 東京ディズニーランド",
        description: "찻잔 모양 탑승체를 타고 빙글빙글 도는 회전 라이드",
        recommendedTime: "약 2분",
        rating: 3,
        indoor: false,
        darkRide: false,
        thrillLevel: 1,
        highlights: ["직접 회전 속도를 조절하는 재미", "이상한 나라의 앨리스를 테마로 한 아기자기한 장식"],
      },
      {
        id: "castle-carrousel",
        name: "캐슬 캐러셀",
        japaneseName: "キャッスルカルーセル",
        category: "attraction",
        area: "판타지랜드",
        coords: [35.6314159, 139.881257],
        googleMapsQuery: "キャッスルカルーセル 東京ディズニーランド",
        description: "신데렐라 성 앞에 위치한 클래식한 회전목마",
        recommendedTime: "약 2분",
        rating: 3,
        indoor: false,
        darkRide: false,
        thrillLevel: 1,
        highlights: ["온 가족이 함께 탈 수 있는 어트랙션", "성 앞이라는 상징적인 포토 스팟"],
      },
      {
        id: "haunted-mansion",
        name: "홀랜티드 맨션",
        japaneseName: "ホーンテッドマンション",
        category: "attraction",
        area: "판타지랜드",
        coords: [35.6312281, 139.881903],
        googleMapsQuery: "ホーンテッドマンション 東京ディズニーランド",
        description: "999명의 유령이 산다는 저택을 탐험하는 코믹 호러 다크라이드",
        recommendedTime: "약 9분",
        rating: 5,
        indoor: true,
        darkRide: true,
        thrillLevel: 2,
        highlights: ["익살스럽고 기묘한 분위기의 연출", "회전하는 방 등 독특한 특수효과"],
      },
      {
        id: "beauty-beast",
        name: "미녀와 야수 \"마법 이야기\"",
        japaneseName: "美女と野獣“魔法のものがたり”",
        category: "attraction",
        area: "판타지랜드",
        coords: [35.631147, 139.8781888],
        googleMapsQuery: "美女と野獣“魔法のものがたり” 東京ディズニーランド",
        description: "벨과 야수의 이야기를 트랙 없는 라이드 차량으로 따라가는 도쿄 디즈니랜드 전용 어트랙션",
        recommendedTime: "약 8분",
        rating: 5,
        indoor: true,
        darkRide: true,
        thrillLevel: 1,
        highlights: ["도쿄 디즈니랜드에서만 만날 수 있는 트랙리스 라이드", "무도회장 왈츠 장면 등 화려한 연출"],
      },
      {
        id: "magical-music-world",
        name: "미키의 매지컬 뮤직 월드",
        japaneseName: "ミッキーのマジカルミュージックワールド",
        category: "attraction",
        area: "판타지랜드",
        coords: [35.6312777, 139.8777727],
        googleMapsQuery: "ミッキーのマジカルミュージックワールド 東京ディズニーランド",
        description: "미키와 친구들이 다양한 음악과 춤으로 꾸미는 라이브 무대쇼(구 '미키의 마법의 음악회' 자리)",
        recommendedTime: "약 25분",
        rating: 3,
        indoor: true,
        darkRide: false,
        thrillLevel: 1,
        highlights: ["미키를 비롯한 캐릭터들의 라이브 공연", "장르가 계속 바뀌는 다채로운 음악 구성"],
      },
      {
        id: "pooh-hunny-hunt",
        name: "곰돌이 푸의 허니 헌트",
        japaneseName: "プーさんのハニーハント",
        category: "attraction",
        area: "판타지랜드",
        coords: [35.630542, 139.8800801],
        googleMapsQuery: "プーさんのハニーハント 東京ディズニーランド",
        description: "꿀단지 모양 트랙리스 차량을 타고 100에이커 숲을 모험하는 어트랙션",
        recommendedTime: "약 4분",
        rating: 5,
        indoor: true,
        darkRide: true,
        thrillLevel: 1,
        highlights: ["예측 불가능하게 움직이는 트랙리스 라이드", "바람 부는 숲 등 사계절 연출"],
      },
      {
        id: "space-mountain",
        name: "스페이스 마운틴",
        japaneseName: "スペース・マウンテン",
        category: "attraction",
        area: "투모로우랜드",
        coords: [35.6323893, 139.877752],
        googleMapsQuery: "スペース・マウンテン 東京ディズニーランド",
        description: "실내 암전 속을 질주하는 우주여행 콘셉트의 롤러코스터",
        recommendedTime: "약 3분",
        rating: 5,
        indoor: true,
        darkRide: true,
        thrillLevel: 3,
        highlights: ["빛과 어둠 속 스릴 만점 코스터", "우주를 여행하는 듯한 몰입감"],
      },
      {
        id: "star-tours",
        name: "스타 투어스: 어드벤처 컨티뉴즈",
        japaneseName: "スター・ツアーズ：ザ・アドベンチャーズ・コンティニュー",
        category: "attraction",
        area: "투모로우랜드",
        coords: [35.6334403, 139.8782291],
        googleMapsQuery: "スター・ツアーズ 東京ディズニーランド",
        description: "스타워즈 세계관 속에서 매번 다른 스토리로 즐기는 시뮬레이터 라이드",
        recommendedTime: "약 5분",
        rating: 4,
        indoor: true,
        darkRide: true,
        thrillLevel: 2,
        highlights: ["매번 랜덤 조합되는 다양한 스토리", "생생한 3D 우주 비행 체험"],
      },
      {
        id: "buzz-lightyear",
        name: "버즈 라이트이어의 아스트로 블래스터",
        japaneseName: "バズ・ライトイヤーのアストロブラスター",
        category: "attraction",
        area: "투모로우랜드",
        coords: [35.6327858, 139.8790569],
        googleMapsQuery: "バズ・ライトイヤーのアストロブラスター 東京ディズニーランド",
        description: "직접 광선총을 조준해 점수를 겨루는 인터랙티브 슈팅 다크라이드",
        recommendedTime: "약 5분",
        rating: 4,
        indoor: true,
        darkRide: true,
        thrillLevel: 2,
        highlights: ["가족끼리 점수 경쟁하며 즐기는 재미", "장난감 나라를 재현한 화려한 세트"],
      },
      {
        id: "monsters-inc-ride-go-seek",
        name: "몬스터 주식회사 \"라이드 & 고 씨크!!\"",
        japaneseName: "モンスターズ・インク“ライド＆ゴーシーク！”",
        category: "attraction",
        area: "투모로우랜드",
        coords: [35.6338811, 139.8784011],
        googleMapsQuery: "モンスターズ・インク ライド＆ゴーシーク 東京ディズニーランド",
        description: "손전등으로 몬스터를 찾아내는 도쿄 디즈니랜드 단독 인터랙티브 다크라이드",
        recommendedTime: "약 4분",
        rating: 4,
        indoor: true,
        darkRide: true,
        thrillLevel: 1,
        highlights: ["도쿄 디즈니랜드에서만 즐길 수 있는 단독 어트랙션", "손전등으로 몬스터를 찾는 게임 요소"],
      },
      {
        id: "baymax-happy-ride",
        name: "베이맥스의 해피 라이드",
        japaneseName: "ベイマックスのハッピーライド",
        category: "attraction",
        area: "투모로우랜드",
        coords: [35.6317263, 139.8788614],
        googleMapsQuery: "ベイマックスのハッピーライド 東京ディズニーランド",
        description: "빅 히어로 6를 테마로 신나는 음악에 맞춰 회전하는 라이드",
        recommendedTime: "약 2분",
        rating: 4,
        indoor: true,
        darkRide: false,
        thrillLevel: 2,
        highlights: ["신나는 음악과 함께하는 회전 라이드", "베이맥스의 귀여운 비주얼"],
      },
      {
        id: "roger-rabbit-cartoon-spin",
        name: "로저 래빗의 카툰 스핀",
        japaneseName: "ロジャーラビットのカートゥーンスピン",
        category: "attraction",
        area: "툰타운",
        coords: [35.6297648, 139.8800262],
        googleMapsQuery: "ロジャーラビットのカートゥーンスピン 東京ディズニーランド",
        description: "택시 모양 탑승체를 직접 돌리며 만화 같은 툰타운을 누비는 스피닝 다크라이드",
        recommendedTime: "약 3분",
        rating: 4,
        indoor: true,
        darkRide: true,
        thrillLevel: 1,
        highlights: ["택시를 직접 돌리며 즐기는 스피닝 라이드", "만화 같은 툰타운 세트 속 추격전"],
      },

      // ----------------------------------------------------------------
      // 레스토랑
      // ----------------------------------------------------------------
      {
        id: "blue-bayou",
        name: "블루 바이유 레스토랑",
        japaneseName: "ブルーバイユー・レストラン",
        category: "restaurant",
        area: "어드벤처랜드",
        coords: [35.6344101, 139.8811923],
        googleMapsQuery: "ブルーバイユー・レストラン 東京ディズニーランド",
        description: "카리브해·뉴올리언스풍 분위기 속에서 즐기는 고급 코스 요리 레스토랑",
        priceRange: "1인 약 7,000엔~ (코스)",
        recommendedTime: "약 60~90분",
        rating: 5,
        highlights: ["카리브의 해적 어트랙션 내부, 별빛 뜬 밤하늘 연출", "완전 예약제에 가까워 사전 예약 강력 권장"],
      },
      {
        id: "queen-of-hearts",
        name: "퀸 오브 하트의 뱅퀫홀",
        japaneseName: "クイーン・オブ・ハートのバンケットホール",
        category: "restaurant",
        area: "판타지랜드",
        coords: [35.6310489, 139.8812591],
        googleMapsQuery: "クイーン・オブ・ハートのバンケットホール 東京ディズニーランド",
        description: "이상한 나라의 앨리스를 테마로 한 카페테리아식 양식 레스토랑",
        priceRange: "1,200~2,300엔",
        recommendedTime: "약 45분",
        rating: 4,
        highlights: ["생일 당일엔 캐스트에게 말하면 'Happy Birthday' 초콜릿 플레이트로 변경 가능", "트럼프 카드 모티브의 화려한 인테리어"],
      },
      {
        id: "diamond-horseshoe",
        name: "더 다이아몬드 호스슈",
        japaneseName: "ザ・ダイヤモンドホースシュー",
        category: "restaurant",
        area: "웨스턴랜드",
        coords: [35.6326228, 139.8816633],
        googleMapsQuery: "ザ・ダイヤモンドホースシュー 東京ディズニーランド",
        description: "쇼를 보며 식사하는 완전 예약제 웨스턴 스타일 코스 레스토랑",
        priceRange: "5,500~6,500엔 (코스)",
        recommendedTime: "약 60분 (쇼 포함)",
        rating: 4,
        highlights: ["점심엔 토이스토리, 저녁엔 미키&미니 등장 쇼 상영", "사전 온라인 예약 필수"],
      },
      {
        id: "crystal-palace",
        name: "크리스탈 팰리스 레스토랑",
        japaneseName: "クリスタルパレス・レストラン",
        category: "restaurant",
        area: "월드바자 인접(퍼레이드 루트변)",
        coords: [35.6335891, 139.8809214],
        googleMapsQuery: "クリスタルパレス・レストラン 東京ディズニーランド",
        description: "파크 내 유일한 뷔페 스타일 레스토랑으로 양식·일식·중식을 두루 즐길 수 있음",
        priceRange: "약 5,000엔 (뷔페)",
        recommendedTime: "약 60분",
        rating: 4,
        highlights: ["2025년 4월 리뉴얼 오픈", "곰돌이 푸 캐릭터와의 그리팅 타임 운영"],
      },
      {
        id: "plaza-pavilion",
        name: "플라자 파빌리온 레스토랑",
        japaneseName: "プラザパビリオン・レストラン",
        category: "restaurant",
        area: "웨스턴랜드",
        coords: [35.6328604, 139.8814464],
        googleMapsQuery: "プラザパビリオン・レストラン 東京ディズニーランド",
        description: "파크 내 가장 큰 야외 파티오를 가진 양식 카페테리아",
        priceRange: "1,300~2,500엔",
        recommendedTime: "약 40분",
        rating: 3,
        highlights: ["퍼레이드 루트 인근이라 식사하며 퍼레이드 관람 가능", "밝은 중정형 파티오 좌석"],
      },
      {
        id: "pan-galactic-pizza",
        name: "팬 갤럭틱 피자 포트",
        japaneseName: "パン・ギャラクティック・ピザ・ポート",
        category: "restaurant",
        area: "투모로우랜드",
        coords: [35.6330921, 139.8786083],
        googleMapsQuery: "パン・ギャラクティック・ピザ・ポート 東京ディズニーランド",
        description: "근미래풍 실내에서 즐기는 피자·칼조네 전문 카운터서비스",
        priceRange: "~1,200엔",
        recommendedTime: "약 30~40분",
        rating: 3,
        highlights: ["에이리언 모양의 '리틀 그린 만쥬' 간식 판매", "약 630석의 넉넉한 좌석"],
      },
      {
        id: "grandma-sara",
        name: "그랜마 사라의 키친",
        japaneseName: "グランマ・サラのキッチン",
        category: "restaurant",
        area: "크리터컨트리",
        coords: [35.6310799, 139.8825518],
        googleMapsQuery: "グランマ・サラのキッチン 東京ディズニーランド",
        description: "스플래시 마운틴 인근의 아늑한 오두막풍 양식 레스토랑",
        priceRange: "1,500~2,000엔",
        recommendedTime: "약 30~40분",
        rating: 3,
        highlights: ["치킨·오므라이스 등 아이 친화적 메뉴", "약 480석으로 혼잡 시에도 비교적 여유"],
      },
      {
        id: "center-street-coffee",
        name: "센터 스트리트 커피하우스",
        japaneseName: "センターストリート・コーヒーハウス",
        category: "restaurant",
        area: "월드바자",
        coords: [35.6341473, 139.8791078],
        googleMapsQuery: "センターストリート・コーヒーハウス 東京ディズニーランド",
        description: "파크 입구 인근에서 아침 식사도 가능한 테이블서비스 양식 레스토랑",
        priceRange: "1,800엔~",
        recommendedTime: "약 40분",
        rating: 3,
        highlights: ["파크 오픈 직후부터 조식 메뉴 운영(몇 안 되는 곳)", "스테이크·샐러드 등 양식 메뉴"],
      },
      {
        id: "tomorrowland-terrace",
        name: "투모로우랜드 테라스",
        japaneseName: "トゥモローランド・テラス",
        category: "restaurant",
        area: "투모로우랜드",
        coords: [35.6319086, 139.8795571],
        googleMapsQuery: "トゥモローランド・テラス 東京ディズニーランド",
        description: "파크 내 최대 규모 좌석의 패스트푸드 레스토랑",
        priceRange: "~1,400엔",
        recommendedTime: "약 30분",
        rating: 3,
        highlights: ["약 1,360석으로 언제나 자리 찾기 수월", "버거·샐러드·츄러스 등 패스트푸드 메뉴, 테이크아웃 가능"],
      },
      {
        id: "hungry-bear",
        name: "헝그리 베어 레스토랑",
        japaneseName: "ハングリーベア・レストラン",
        category: "restaurant",
        area: "웨스턴랜드",
        coords: [35.632565, 139.8829169],
        googleMapsQuery: "ハングリーベア・レストラン 東京ディズニーランド",
        description: "카레를 전문으로 하는 대형 카운터서비스 레스토랑",
        priceRange: "900엔~",
        recommendedTime: "약 30분",
        rating: 3,
        highlights: ["약 690석의 넓은 좌석 규모", "다양한 카레 메뉴"],
      },

      // ----------------------------------------------------------------
      // 샵
      // ----------------------------------------------------------------
      {
        id: "world-bazaar-emporium",
        name: "그랜드 엠포리엄",
        japaneseName: "グランドエンポーリアム",
        category: "shop",
        area: "월드바자",
        coords: [35.6343991, 139.8793314],
        googleMapsQuery: "グランドエンポーリアム 東京ディズニーランド",
        description: "파크 최대 규모의 종합 기념품샵으로 캐릭터 인형, 의류, 문구, 과자 등 거의 모든 종류의 디즈니 굿즈를 판매",
        recommendedTime: "약 20~30분",
        rating: 4,
        highlights: ["파크 내 가장 넓은 매장", "폐장 후에도 다른 매장보다 늦게까지 영업"],
      },
      {
        id: "world-bazaar-confectionery",
        name: "월드바자 콘펙셔너리",
        japaneseName: "ワールドバザール・コンフェクショナリー",
        category: "shop",
        area: "월드바자",
        coords: [35.6344658, 139.8797084],
        googleMapsQuery: "ワールドバザール・コンフェクショナリー 東京ディズニーランド",
        description: "디즈니 캐릭터 쿠키, 초콜릿, 캔디 등 과자류를 전문으로 판매하는 기념품샵",
        recommendedTime: "약 10~15분",
        rating: 3,
        highlights: ["선물용 소포장 과자 상품이 다양함", "그랜드 엠포리엄 바로 옆이라 함께 둘러보기 좋음"],
      },
      {
        id: "poohs-corner",
        name: "푸의 코너",
        japaneseName: "プーさんコーナー",
        category: "shop",
        area: "판타지랜드",
        coords: [35.6306703, 139.8804853],
        googleMapsQuery: "プーさんコーナー 東京ディズニーランド",
        description: "곰돌이 푸와 친구들 테마의 인형, 잡화, 문구를 전문으로 판매하는 기념품샵",
        recommendedTime: "약 15~20분",
        rating: 4,
        highlights: ["푸의 허니 헌트 어트랙션과 인접", "푸 캐릭터 한정 굿즈가 특히 풍부"],
      },
      {
        id: "kingdom-treasures",
        name: "킹덤 트레저",
        japaneseName: "キングダム・トレジャー",
        category: "shop",
        area: "판타지랜드 (신데렐라성 인근)",
        coords: [35.6319274, 139.8811937],
        googleMapsQuery: "キングダム・トレジャー 東京ディズニーランド",
        description: "디즈니 프린세스 테마 드레스, 액세서리, 잡화를 전문으로 판매하는 기념품샵",
        recommendedTime: "약 15~20분",
        rating: 3,
        highlights: ["신데렐라성 바로 근처라 드레스업 후 방문하기 좋음", "여자아이들에게 인기 높은 프린세스 굿즈 다수 보유"],
      },
      {
        id: "cosmic-encounter",
        name: "코스믹 인카운터",
        japaneseName: "コズミック・エンカウンター",
        category: "shop",
        area: "투모로우랜드",
        coords: [35.6335291, 139.8786817],
        googleMapsQuery: "コズミック・エンカウンター 東京ディズニーランド",
        description: "스타워즈 및 SF 테마 굿즈와 알파벳 큐브 커스텀 키체인·스트랩 제작을 전문으로 하는 기념품샵",
        recommendedTime: "약 10~15분",
        rating: 3,
        highlights: ["스타투어스: 어드벤처 컨티뉴 탑승구 바로 앞", "알파벳 금속 큐브로 나만의 키체인 제작 가능"],
      },
      {
        id: "toontown-five-and-dime",
        name: "개그 팩토리 / 파이브 앤 다임",
        japaneseName: "ギャグファクトリー／ファイブ・アンド・ダイム",
        category: "shop",
        area: "툰타운",
        coords: [35.6299537, 139.8801987],
        googleMapsQuery: "ギャグファクトリー/ファイブ・アンド・ダイム 東京ディズニーランド",
        description: "미키, 미니 등 툰타운 캐릭터 테마의 잡화와 장난감을 판매하는 종합 기념품샵",
        recommendedTime: "약 15~20분",
        rating: 3,
        highlights: ["툰타운 캐릭터 그리팅 시설 관람 후 들르기 좋은 위치", "가챠(캡슐토이) 코너도 함께 운영"],
      },

      // ----------------------------------------------------------------
      // 화장실 — 공식 파크 가이드맵(TDL_map_kr.pdf)에서 각 랜드마다 화장실
      // 아이콘이 있는 것을 확인했다. 손그림 스타일 지도라 정확한 픽셀 좌표를
      // 실제 좌표로 환산하는 건 오독 위험이 커서, 새 좌표를 추정하는 대신
      // 이미 구글맵으로 검증된 각 랜드 중심부의 실제 좌표를 그대로 재사용했다
      // ("이 근처에 화장실이 있다"는 랜드 단위 근사치). verified:false와
      // source로 이 출처를 명시한다. 다목적 화장실 여부 등 세부 시설 정보는
      // 지도에서 정확히 구분할 수 없어 null(확인 필요)로 남겨둔다.
      // ----------------------------------------------------------------
      {
        id: "restroom-world-bazaar",
        name: "월드바자 화장실",
        category: "restroom",
        area: "월드바자",
        coords: [35.6343991, 139.8793314],
        approximate: true,
        verified: false,
        source: "TDL_map_kr.pdf (랜드 단위 근사, 좌표는 그랜드 엠포리엄 앵커)",
        description: "공식 가이드맵 기준 월드바자 구역 화장실 위치(그랜드 엠포리엄 인근) — 정확한 개별 GPS는 미검증",
        recommendedTime: "약 5분",
        multiPurpose: null,
        diaperChanging: null,
        kidsFacility: null,
        nearBabyCenter: null,
      },
      {
        id: "restroom-adventureland",
        name: "어드벤처랜드 화장실",
        category: "restroom",
        area: "어드벤처랜드",
        coords: [35.6342439, 139.8807329],
        approximate: true,
        verified: false,
        source: "TDL_map_kr.pdf (랜드 단위 근사, 좌표는 카리브의 해적 앵커)",
        description: "공식 가이드맵 기준 어드벤처랜드 구역 화장실 위치(카리브의 해적 인근) — 정확한 개별 GPS는 미검증",
        recommendedTime: "약 5분",
        multiPurpose: null,
        diaperChanging: null,
        kidsFacility: null,
        nearBabyCenter: null,
      },
      {
        id: "restroom-westernland",
        name: "웨스턴랜드 화장실",
        category: "restroom",
        area: "웨스턴랜드",
        coords: [35.6326228, 139.8816633],
        approximate: true,
        verified: false,
        source: "TDL_map_kr.pdf (랜드 단위 근사, 좌표는 더 다이아몬드 호스슈 앵커)",
        description: "공식 가이드맵 기준 웨스턴랜드 구역 화장실 위치(더 다이아몬드 호스슈 인근) — 정확한 개별 GPS는 미검증",
        recommendedTime: "약 5분",
        multiPurpose: null,
        diaperChanging: null,
        kidsFacility: null,
        nearBabyCenter: null,
      },
      {
        id: "restroom-critter-country",
        name: "크리터컨트리 화장실",
        category: "restroom",
        area: "크리터컨트리",
        coords: [35.6310799, 139.8825518],
        approximate: true,
        verified: false,
        source: "TDL_map_kr.pdf (랜드 단위 근사, 좌표는 그랜마 사라의 키친 앵커)",
        description: "공식 가이드맵 기준 크리터컨트리 구역 화장실 위치(그랜마 사라의 키친 인근) — 정확한 개별 GPS는 미검증",
        recommendedTime: "약 5분",
        multiPurpose: null,
        diaperChanging: null,
        kidsFacility: null,
        nearBabyCenter: null,
      },
      {
        id: "restroom-fantasyland",
        name: "판타지랜드 화장실",
        category: "restroom",
        area: "판타지랜드",
        coords: [35.630542, 139.8800801],
        approximate: true,
        verified: false,
        source: "TDL_map_kr.pdf (랜드 단위 근사, 좌표는 곰돌이 푸의 허니 헌트 앵커)",
        description: "공식 가이드맵 기준 판타지랜드 구역 화장실 위치(곰돌이 푸의 허니 헌트 인근) — 정확한 개별 GPS는 미검증",
        recommendedTime: "약 5분",
        multiPurpose: null,
        diaperChanging: null,
        kidsFacility: null,
        nearBabyCenter: null,
      },
      {
        id: "restroom-toontown",
        name: "툰타운 화장실",
        category: "restroom",
        area: "툰타운",
        coords: [35.6299537, 139.8801987],
        approximate: true,
        verified: false,
        source: "TDL_map_kr.pdf (랜드 단위 근사, 좌표는 개그 팩토리/파이브 앤 다임 앵커)",
        description: "공식 가이드맵 기준 툰타운 구역 화장실 위치(개그 팩토리/파이브 앤 다임 인근) — 정확한 개별 GPS는 미검증",
        recommendedTime: "약 5분",
        multiPurpose: null,
        diaperChanging: null,
        kidsFacility: null,
        nearBabyCenter: null,
      },
      {
        id: "restroom-tomorrowland",
        name: "투머로우랜드 화장실",
        category: "restroom",
        area: "투머로우랜드",
        coords: [35.6319086, 139.8795571],
        approximate: true,
        verified: false,
        source: "TDL_map_kr.pdf (랜드 단위 근사, 좌표는 투머로우랜드 테라스 앵커)",
        description: "공식 가이드맵 기준 투머로우랜드 구역 화장실 위치(투머로우랜드 테라스 인근) — 정확한 개별 GPS는 미검증",
        recommendedTime: "약 5분",
        multiPurpose: null,
        diaperChanging: null,
        kidsFacility: null,
        nearBabyCenter: null,
      },
    ],
  },

  tds: {
    key: "tds",
    name: "도쿄 디즈니씨",
    // TDS_map_kr.pdf를 열어 8개 테마포트 구조(미디터레이니언 하버·아메리칸
    // 워터프론트·포트 디스커버리·로스트 리버 델타·아라비안 코스트·머메이드
    // 라군·미스테리어스 아일랜드·판타지 스프링스)와 주요 어트랙션 이름은
    // 파악했지만, 이 좌표는 구글맵으로 검증되지 않은 리조트 지역 대략치일
    // 뿐이며 개별 시설 위치가 아니다 — 지도를 열었을 때 카메라 위치용으로만
    // 쓰고, 시설 데이터가 채워지기 전까지 facilities는 비워둔다.
    coords: [35.6267, 139.8853],
    coordsVerified: false,
    mapPdf: "TDS_map_kr.pdf",
    facilities: [],
  },
};
